[package]
name = "quicd-h3"
version = "0.1.0"
edition = "2021"

[dependencies]
quicd-x = { path = "../quicd-x" }
quicd-qpack = { path = "../quicd-qpack" }
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
futures = "0.3"
async-trait = "0.1"
thiserror = "1.0"
http = "0.2"
slab = "0.4"
serde = { version = "1", features = ["derive"] }
humantime-serde = "1"

[dev-dependencies]
criterion = "0.5"
