[package]
name = "quicd-h3"
version = "0.1.0"
edition = "2021"

[dependencies]
quicd-x = { path = "../quicd-x" }
quicd-qpack = { path = "../quicd-qpack" }
tokio = { workspace = true, features = ["full"] }
bytes = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
http = { workspace = true }
slab = { workspace = true }
serde = { workspace = true, features = ["derive"] }
humantime-serde = { workspace = true }
mio = { workspace = true, features = ["net", "os-poll"] }

[dev-dependencies]
criterion = { workspace = true }
