[package]
name = "quicd-h3"
version = "0.1.0"
edition = "2021"

[dependencies]
quicd-x = { path = "../quicd-x" }
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }
tracing = "0.1"
h3 = { version = "0.0.8", features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"] }
http = "1"
bytes = "1"
pin-project-lite = "0.2"
parking_lot = "0.12"
thiserror = "1"
