[package]
name = "quicd-x"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
tokio = { workspace = true, features = ["io-util", "sync", "time", "rt"] }
thiserror = { workspace = true }
