[package]
name = "quicd-x"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["rt", "rt-multi-thread", "sync"] }
async-trait = "0.1"
bytes = "1.9"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5"
