[package]
name = "quicd-quic"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
ring = { workspace = true }
rustls = { workspace = true }
thiserror = { workspace = true }
smallvec = { workspace = true }
ahash = { workspace = true }
log = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "test-util"] }
rcgen = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }
